# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of MiracleTools
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/awalki/MiracleTools/
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use the MiniMessage <#123456> syntax: "Hello <#123456>world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding
#
#    5) WHITELISTS can be turned into blacklists, by putting "@blacklist" on the first line.
#       - Doing such, filters will only apply for messages in those lists.
#
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Suffixes
# -------------------------------------------------------------------------------------------------
Suffix:

  # Should add whitespace between suffix and nickname
  Whitespace: false

  # List of suffixes
  List:

    # -------------------------------------------------------------------------------------------------
    # Format: How suffix will be shown
    # Permission: Access to suffix through permission
    # Example of correct permission: [miracletools.suffix] + name of suffix which compares with key
    # -------------------------------------------------------------------------------------------------
    star:
      Format: "&e⭐"
      Permission: "miracletools.suffix.star"
    heart:
      Format: "&c❤"
      Permission: "miracletools.suffix.heart"

# -------------------------------------------------------------------------------------------------
# HideNameTag (Depends TAB plugin. Enabling invisible-nametags is important to hide tags)
# -------------------------------------------------------------------------------------------------
HideNameTag:

  # Black List [Black List message may customize in en_US.json make dump first /mt dumplocale]
  Blacklist:
    - "je3ns"

# -------------------------------------------------------------------------------------------------
# Observer (Sends a notification when the player breaks the selected block from array )
# -------------------------------------------------------------------------------------------------
Observer:

  # To allow listen give the "miracletools.observer.listen" permission to the player
  Blocks:
    - "DIAMOND_ORE"
    - "DEEPSLATE_DIAMOND_ORE"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
# -------------------------------------------------------------------------------------------------
Command_Aliases: [miracletools, mt]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? Use the "dumplocale" subcommand to move the file
# to your plugin's folder so you can edit it easily.
#
# Available: en_US (English)
# -------------------------------------------------------------------------------------------------
Locale: en_US

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages. You can manually use it with
# {prefix_plugin} variable anywhere.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&c${project.name}&8]&7"

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured. You can also use the LagCatcher class to invoke
# this feature. We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Should we notify you about new versions of the plugin to players with pluginName.update.notify
# permission and the console on startup?
# -------------------------------------------------------------------------------------------------
#Notify_New_Versions: true # requires you to override getBuiltByBitX methods in main plugin's class

# -------------------------------------------------------------------------------------------------
# Send anonymized error reports to sentry.io? This helps us fix bugs without you needing to
# report them manually.
# -------------------------------------------------------------------------------------------------
#Sentry: true # override getSentryDsn() in main plugin's class

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about this plugin's features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: []